### ISSUE TITLE
Serial TX and RX port defines don't match when using Yotta

### ISSUE THREAD

**Issue by ernotormikoski** [ARMmbed/example-asynch-serial#17]
In Yotta build (target as frdm-k64f-gcc) TEST_SERIAL_ONE_TX_PIN and TEST_SERIAL_TWO_RX_PIN defined does not exist in serial_asynch.cpp. Instead there are defines YOTTA_CFG_HARDWARE_TEST_PINS_SERIAL_TX and YOTTA_CFG_HARDWARE_TEST_PINS_SERIAL_RX.

Actually I needed to find these correct pins to connect (RX and TX) from yotta_config.h because in schema it was bit unclear where to connect (YOTTA_CFG_HARDWARE_TEST_PINS_SERIAL_TX PTC17 and YOTTA_CFG_HARDWARE_TEST_PINS_SERIAL_RX PTD2) wire. Rx part was bit confusing so I think it would be good to inform to check from yotta_config.h.

After successfully wiring I got correct trace:
Starting short transfer test
Res is 0
Res is 0
Short transfer DONE, event is 256
Starting long transfer test
Res is 0
Res is 0
Long transfer DONE, event is 256
**** Test done ****

**Comment by 0xc0170** [comment]
Thanks for reporting. There's a pull request, which I commented on. I'll check again, and do some improvements  as we need it. The same should be applied for other asynch examples.

I'll close this once that PR is merged and the requested information are in Readme.

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1103

**Comment by 0xc0170** [comment]
Fixed via #16
