### ISSUE TITLE
Linker issue:  undefined reference to mbed::SerialBase::write and mbed::SerialBase::read

### ISSUE THREAD

**Issue by rklobo** [ARMmbed/example-asynch-serial#19]
The build fails with the below linker issue 
 undefined reference to mbed::SerialBase::read(void*, int, mbed::util::FunctionPointer2<void, mbed::Buffer, int> const&, int, unsigned char)
undefined reference to `mbed::SerialBase::write(void*, int, mbed::util::FunctionPointer2<void, mbed::Buffer, int> const&, int, unsigned char)

This issue is observed when the target selected is nrf51dk-gcc.
Can someone reproduce the issue and possibly provide a fix

Thanks

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1908

**Comment by 0xc0170** [comment]
It's caused because the platform does not support asynch serial. We shall think about better notification for a user in this case

**Comment by 0xc0170** [comment]
@rklobo However, I remembered, the app source handles this case. If there's no serial async support for a target, it prints that this example is not supported. Did you modify the source file?

I just tested mkit-gcc and nrf51dk-gcc, the example builds and should not run any async operations.

**Comment by rklobo** [comment]
@0xc0170  Yes, I did modify the source file to enable serial asynch SerialTest. I understand that on nRF51DK we have only one UART peripheral and cannot be used to print debug statements on PC. However, if I am right, it must support asynch serial (UART) transfer between pins p11 and p9 (as mentioned in target.json) because the UART peripheral supports interrupt based transfer. 

Please let me know if I'm getting something wrong over here. Thanks

**Comment by 0xc0170** [comment]
Please request this for nrf51 targets HAL (https://github.com/ARMmbed/mbed-hal-nrf51822-mcu), as a feature request. That's the repo where it needs to be implemented.

I'll close this issue.
